all: version asserts incidents packets configuration

version:
	cd test_version; make

asserts:
	cd test_asserts; make

incidents:
	cd test_incidents; make

packets:
	cd test_packets; make

configuration:
	cd test_configuration; make

clean: 
	cd test_version; make clean
	cd test_asserts; make clean
	cd test_incidents; make clean
	cd test_packets; make clean
	cd test_configuration; make clean
